import type { CatalogDeveloper, CatalogProject } from "../types";

export const BENGALURU_DEVELOPERS: CatalogDeveloper[] = [
  {
    slug: "brigade-group",
    name: "Brigade Group",
    shortName: "Brigade",
    foundedYear: 1986,
    summary:
      "Large listed Bengaluru promoter with residential, commercial and hospitality across Whitefield, North Bengaluru and the Mysore Road belt.",
  },
  {
    slug: "prestige-group",
    name: "Prestige Group",
    shortName: "Prestige",
    foundedYear: 1986,
    summary:
      "Volume residential and mixed-use developer with a deep East and South Bengaluru footprint, including Lakeside Habitat and several ongoing townships.",
  },
  {
    slug: "sobha-limited",
    name: "Sobha Limited",
    shortName: "Sobha",
    foundedYear: 1995,
    summary:
      "Integrated contractor-developer known for in-house construction. Strong presence in Whitefield, Sarjapur, Thanisandra and Electronic City corridors.",
  },
  {
    slug: "sumadhura-infracon",
    name: "Sumadhura Infracon",
    shortName: "Sumadhura",
    foundedYear: 1995,
    summary:
      "Hyderabad-origin group with a large Bengaluru book in Whitefield, Sarjapur and the ORR catchment. Catalogued separately from Salarpuria Sattva.",
  },
  {
    slug: "godrej-properties",
    name: "Godrej Properties",
    shortName: "Godrej",
    foundedYear: 1990,
    summary:
      "National listed developer with multiple Bengaluru launches on Sarjapur, Whitefield, North Bengaluru and Kanakapura corridors.",
  },
  {
    slug: "salarpuria-sattva",
    name: "Salarpuria Sattva Group",
    shortName: "Sattva",
    foundedYear: 1988,
    summary:
      "Bengaluru-headquartered group (Salarpuria Sattva) with apartments and plotted inventory across East, North and South Bengaluru.",
  },
  {
    slug: "embassy-group",
    name: "Embassy Group",
    shortName: "Embassy",
    foundedYear: 1993,
    summary:
      "Known for offices; residential includes Embassy Springs township, Hebbal lake-facing towers and select plotted offerings.",
  },
  {
    slug: "puravankara",
    name: "Puravankara Limited",
    shortName: "Puravankara",
    foundedYear: 1975,
    summary:
      "Listed Bengaluru-origin developer (Purva / Provident brands) with apartments across North, East and South Bengaluru.",
  },
  {
    slug: "assetz-property",
    name: "Assetz Property Group",
    shortName: "Assetz",
    foundedYear: 2006,
    summary:
      "Bengaluru specialist known for Whitefield and East-ORR communities (Marq, 63° East, Canvas & Cove).",
  },
  {
    slug: "shriram-properties",
    name: "Shriram Properties",
    shortName: "Shriram",
    foundedYear: 1995,
    summary:
      "Listed mid-market residential developer with Whitefield, South and West Bengaluru inventory.",
  },
  {
    slug: "total-environment",
    name: "Total Environment Building Systems",
    shortName: "Total Environment",
    foundedYear: 1996,
    summary:
      "Design-led Bengaluru developer (After the Rain, Pursuit of Radical Rhapsody, Learning to Fly) with a smaller, premium book.",
  },
  {
    slug: "mantri-developers",
    name: "Mantri Developers",
    shortName: "Mantri",
    foundedYear: 1999,
    summary:
      "Bengaluru promoter with a mixed delivery record on large communities; catalogued for coverage, not as an endorsement.",
  },
];

function unverified(developer: string, serial: string) {
  return `UNVERIFIED/KA/${developer}/${serial}`;
}

export const BENGALURU_PROJECTS: CatalogProject[] = [
  {
    key: "brigade:cornerstone-utopia",
    slug: "brigade-cornerstone-utopia",
    name: "Brigade Cornerstone Utopia",
    locality: "Varthur / Whitefield",
    developerSlug: "brigade-group",
    projectType: "APARTMENT",
    totalUnits: 4200,
    reraId: unverified("BRIGADE", "001"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2017-06-15",
    validUntil: "2027-06-14",
    promisedPossession: "2024-12-31",
  },
  {
    key: "brigade:el-dorado",
    slug: "brigade-el-dorado",
    name: "Brigade El Dorado",
    locality: "Bagalur",
    developerSlug: "brigade-group",
    projectType: "APARTMENT",
    totalUnits: 1800,
    reraId: unverified("BRIGADE", "002"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2018-03-10",
    validUntil: "2026-12-31",
    promisedPossession: "2025-06-30",
  },
  {
    key: "brigade:atmosphere",
    slug: "brigade-atmosphere",
    name: "Brigade Atmosphere",
    locality: "Devanahalli",
    developerSlug: "brigade-group",
    projectType: "APARTMENT",
    totalUnits: 900,
    reraId: unverified("BRIGADE", "003"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2019-08-01",
    validUntil: "2027-07-31",
    promisedPossession: "2026-03-31",
  },
  {
    key: "brigade:orchards",
    slug: "brigade-orchards",
    name: "Brigade Orchards",
    locality: "Devanahalli",
    developerSlug: "brigade-group",
    projectType: "MIXED",
    totalUnits: 2500,
    reraId: unverified("BRIGADE", "004"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2016-01-20",
    validUntil: "2026-01-19",
    promisedPossession: "2023-12-31",
    actualPossession: "2024-06-30",
  },
  {
    key: "brigade:exotica",
    slug: "brigade-exotica",
    name: "Brigade Exotica",
    locality: "Old Madras Road",
    developerSlug: "brigade-group",
    projectType: "APARTMENT",
    totalUnits: 560,
    reraId: unverified("BRIGADE", "005"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2015-11-02",
    validUntil: "2024-11-01",
    promisedPossession: "2021-12-31",
    actualPossession: "2022-03-31",
  },
  {
    key: "brigade:panorama",
    slug: "brigade-panorama",
    name: "Brigade Panorama",
    locality: "Mysore Road",
    developerSlug: "brigade-group",
    projectType: "APARTMENT",
    totalUnits: 720,
    reraId: unverified("BRIGADE", "006"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2021-02-12",
    validUntil: "2027-02-11",
    promisedPossession: "2026-12-31",
  },
  {
    key: "brigade:oasis",
    slug: "brigade-oasis",
    name: "Brigade Oasis",
    locality: "Yelahanka",
    developerSlug: "brigade-group",
    projectType: "VILLA",
    totalUnits: 180,
    reraId: unverified("BRIGADE", "007"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2020-09-18",
    validUntil: "2026-09-17",
    promisedPossession: "2025-09-30",
  },
  {
    key: "brigade:komarla-heights",
    slug: "brigade-komarla-heights",
    name: "Brigade Komarla Heights",
    locality: "Rajarajeshwari Nagar",
    developerSlug: "brigade-group",
    projectType: "APARTMENT",
    totalUnits: 430,
    reraId: unverified("BRIGADE", "008"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2022-04-08",
    validUntil: "2027-04-07",
    promisedPossession: "2027-03-31",
  },
  {
    key: "prestige:lakeside-habitat",
    slug: "prestige-lakeside-habitat",
    name: "Prestige Lakeside Habitat",
    locality: "Varthur",
    developerSlug: "prestige-group",
    projectType: "APARTMENT",
    totalUnits: 3400,
    reraId: unverified("PRESTIGE", "001"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2016-05-20",
    validUntil: "2025-12-31",
    promisedPossession: "2022-12-31",
    actualPossession: "2023-06-30",
  },
  {
    key: "prestige:song-of-the-south",
    slug: "prestige-song-of-the-south",
    name: "Prestige Song of the South",
    locality: "Begur",
    developerSlug: "prestige-group",
    projectType: "APARTMENT",
    totalUnits: 1400,
    reraId: unverified("PRESTIGE", "002"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2017-09-01",
    validUntil: "2026-08-31",
    promisedPossession: "2023-12-31",
    actualPossession: "2024-09-30",
  },
  {
    key: "prestige:finsbury-park",
    slug: "prestige-finsbury-park",
    name: "Prestige Finsbury Park",
    locality: "Bagalur",
    developerSlug: "prestige-group",
    projectType: "APARTMENT",
    totalUnits: 2100,
    reraId: unverified("PRESTIGE", "003"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2018-07-14",
    validUntil: "2027-07-13",
    promisedPossession: "2025-12-31",
  },
  {
    key: "prestige:falcon-city",
    slug: "prestige-falcon-city",
    name: "Prestige Falcon City",
    locality: "Kanakapura Road",
    developerSlug: "prestige-group",
    projectType: "APARTMENT",
    totalUnits: 1700,
    reraId: unverified("PRESTIGE", "004"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2016-11-08",
    validUntil: "2025-11-07",
    promisedPossession: "2022-06-30",
    actualPossession: "2023-03-31",
  },
  {
    key: "prestige:park-grove",
    slug: "prestige-park-grove",
    name: "Prestige Park Grove",
    locality: "Whitefield",
    developerSlug: "prestige-group",
    projectType: "APARTMENT",
    totalUnits: 980,
    reraId: unverified("PRESTIGE", "005"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2021-01-22",
    validUntil: "2027-01-21",
    promisedPossession: "2026-06-30",
  },
  {
    key: "prestige:lavender-fields",
    slug: "prestige-lavender-fields",
    name: "Prestige Lavender Fields",
    locality: "Sarjapur Road",
    developerSlug: "prestige-group",
    projectType: "APARTMENT",
    totalUnits: 640,
    reraId: unverified("PRESTIGE", "006"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2022-06-03",
    validUntil: "2027-06-02",
    promisedPossession: "2027-03-31",
  },
  {
    key: "prestige:raintree-park",
    slug: "prestige-waterford",
    name: "Prestige Waterford",
    locality: "Whitefield",
    developerSlug: "prestige-group",
    projectType: "APARTMENT",
    totalUnits: 420,
    reraId: unverified("PRESTIGE", "007"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2019-04-16",
    validUntil: "2026-04-15",
    promisedPossession: "2024-12-31",
  },
  {
    key: "prestige:fairfield",
    slug: "prestige-fairfield",
    name: "Prestige Fairfield",
    locality: "Whitefield",
    developerSlug: "prestige-group",
    projectType: "APARTMENT",
    totalUnits: 310,
    reraId: unverified("PRESTIGE", "008"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2020-10-09",
    validUntil: "2026-10-08",
    promisedPossession: "2025-09-30",
  },
  {
    key: "sobha:dream-gardens",
    slug: "sobha-dream-gardens",
    name: "Sobha Dream Gardens",
    locality: "Thanisandra",
    developerSlug: "sobha-limited",
    projectType: "APARTMENT",
    totalUnits: 1600,
    reraId: unverified("SOBHA", "001"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2017-02-11",
    validUntil: "2026-02-10",
    promisedPossession: "2024-06-30",
  },
  {
    key: "sobha:royal-pavilion",
    slug: "sobha-royal-pavilion",
    name: "Sobha Royal Pavilion",
    locality: "Sarjapur Road",
    developerSlug: "sobha-limited",
    projectType: "APARTMENT",
    totalUnits: 980,
    reraId: unverified("SOBHA", "002"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2018-08-24",
    validUntil: "2026-08-23",
    promisedPossession: "2025-03-31",
  },
  {
    key: "sobha:neopolis",
    slug: "sobha-neopolis",
    name: "Sobha Neopolis",
    locality: "Panathur",
    developerSlug: "sobha-limited",
    projectType: "APARTMENT",
    totalUnits: 1200,
    reraId: unverified("SOBHA", "003"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2021-11-30",
    validUntil: "2027-11-29",
    promisedPossession: "2027-06-30",
  },
  {
    key: "sobha:windsor",
    slug: "sobha-windsor",
    name: "Sobha Windsor",
    locality: "Whitefield",
    developerSlug: "sobha-limited",
    projectType: "APARTMENT",
    totalUnits: 540,
    reraId: unverified("SOBHA", "004"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2015-06-18",
    validUntil: "2023-06-17",
    promisedPossession: "2020-12-31",
    actualPossession: "2021-03-31",
  },
  {
    key: "sobha:silicon-oasis",
    slug: "sobha-silicon-oasis",
    name: "Sobha Silicon Oasis",
    locality: "Hosur Road",
    developerSlug: "sobha-limited",
    projectType: "APARTMENT",
    totalUnits: 1100,
    reraId: unverified("SOBHA", "005"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2016-03-07",
    validUntil: "2025-03-06",
    promisedPossession: "2022-12-31",
    actualPossession: "2023-09-30",
  },
  {
    key: "sobha:city",
    slug: "sobha-city-thanisandra",
    name: "Sobha City",
    locality: "Thanisandra",
    developerSlug: "sobha-limited",
    projectType: "MIXED",
    totalUnits: 800,
    reraId: unverified("SOBHA", "006"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2014-09-12",
    validUntil: "2024-09-11",
    promisedPossession: "2019-12-31",
    actualPossession: "2020-06-30",
  },
  {
    key: "sobha:sentosa",
    slug: "sobha-sentosa",
    name: "Sobha Sentosa",
    locality: "Kengeri",
    developerSlug: "sobha-limited",
    projectType: "APARTMENT",
    totalUnits: 360,
    reraId: unverified("SOBHA", "007"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2022-01-19",
    validUntil: "2027-01-18",
    promisedPossession: "2026-12-31",
  },
  {
    key: "sumadhura:folium",
    slug: "sumadhura-folium",
    name: "Sumadhura Folium",
    locality: "Whitefield",
    developerSlug: "sumadhura-infracon",
    projectType: "APARTMENT",
    totalUnits: 720,
    reraId: unverified("SUMADHURA", "001"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2021-05-04",
    validUntil: "2027-05-03",
    promisedPossession: "2026-09-30",
  },
  {
    key: "sumadhura:sushantham",
    slug: "sumadhura-sushantham",
    name: "Sumadhura Sushantham",
    locality: "Sarjapur Road",
    developerSlug: "sumadhura-infracon",
    projectType: "APARTMENT",
    totalUnits: 480,
    reraId: unverified("SUMADHURA", "002"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2020-02-14",
    validUntil: "2026-02-13",
    promisedPossession: "2025-03-31",
  },
  {
    key: "sumadhura:nandanam",
    slug: "sumadhura-nandanam",
    name: "Sumadhura Nandanam",
    locality: "Whitefield",
    developerSlug: "sumadhura-infracon",
    projectType: "APARTMENT",
    totalUnits: 390,
    reraId: unverified("SUMADHURA", "003"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2018-10-22",
    validUntil: "2025-10-21",
    promisedPossession: "2023-12-31",
    actualPossession: "2024-08-31",
  },
  {
    key: "sumadhura:capitol-residences",
    slug: "sumadhura-capitol-residences",
    name: "Sumadhura Capitol Residences",
    locality: "Whitefield",
    developerSlug: "sumadhura-infracon",
    projectType: "APARTMENT",
    totalUnits: 610,
    reraId: unverified("SUMADHURA", "004"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2019-07-01",
    validUntil: "2026-06-30",
    promisedPossession: "2025-06-30",
  },
  {
    key: "sumadhura:gardenia",
    slug: "sumadhura-gardenia",
    name: "Sumadhura Gardenia",
    locality: "Whitefield",
    developerSlug: "sumadhura-infracon",
    projectType: "APARTMENT",
    totalUnits: 280,
    reraId: unverified("SUMADHURA", "005"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2016-12-09",
    validUntil: "2024-12-08",
    promisedPossession: "2021-12-31",
    actualPossession: "2022-06-30",
  },
  {
    key: "sumadhura:aspire",
    slug: "sumadhura-aspire",
    name: "Sumadhura Aspire",
    locality: "Whitefield",
    developerSlug: "sumadhura-infracon",
    projectType: "APARTMENT",
    totalUnits: 340,
    reraId: unverified("SUMADHURA", "006"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2023-03-18",
    validUntil: "2028-03-17",
    promisedPossession: "2027-12-31",
  },
  {
    key: "godrej:splendour",
    slug: "godrej-splendour",
    name: "Godrej Splendour",
    locality: "Whitefield",
    developerSlug: "godrej-properties",
    projectType: "APARTMENT",
    totalUnits: 1100,
    reraId: unverified("GODREJ", "001"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2019-01-25",
    validUntil: "2026-01-24",
    promisedPossession: "2025-06-30",
  },
  {
    key: "godrej:woodscapes",
    slug: "godrej-woodscapes",
    name: "Godrej Woodscapes",
    locality: "Whitefield",
    developerSlug: "godrej-properties",
    projectType: "APARTMENT",
    totalUnits: 1500,
    reraId: unverified("GODREJ", "002"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2022-09-12",
    validUntil: "2028-09-11",
    promisedPossession: "2027-12-31",
  },
  {
    key: "godrej:park-retreat",
    slug: "godrej-park-retreat",
    name: "Godrej Park Retreat",
    locality: "Sarjapur Road",
    developerSlug: "godrej-properties",
    projectType: "APARTMENT",
    totalUnits: 860,
    reraId: unverified("GODREJ", "003"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2020-06-05",
    validUntil: "2026-06-04",
    promisedPossession: "2025-12-31",
  },
  {
    key: "godrej:ananda",
    slug: "godrej-ananda",
    name: "Godrej Ananda",
    locality: "Bagalur",
    developerSlug: "godrej-properties",
    projectType: "APARTMENT",
    totalUnits: 1900,
    reraId: unverified("GODREJ", "004"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2021-08-20",
    validUntil: "2027-08-19",
    promisedPossession: "2026-12-31",
  },
  {
    key: "godrej:eternity",
    slug: "godrej-eternity",
    name: "Godrej Eternity",
    locality: "Kanakapura Road",
    developerSlug: "godrej-properties",
    projectType: "APARTMENT",
    totalUnits: 720,
    reraId: unverified("GODREJ", "005"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2018-04-27",
    validUntil: "2025-04-26",
    promisedPossession: "2023-12-31",
    actualPossession: "2024-12-31",
  },
  {
    key: "godrej:royale-woods",
    slug: "godrej-royale-woods",
    name: "Godrej Royale Woods",
    locality: "Bagalur",
    developerSlug: "godrej-properties",
    projectType: "APARTMENT",
    totalUnits: 640,
    reraId: unverified("GODREJ", "006"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2023-01-11",
    validUntil: "2028-01-10",
    promisedPossession: "2027-09-30",
  },
  {
    key: "sattva:east-crest",
    slug: "salarpuria-sattva-east-crest",
    name: "Salarpuria Sattva East Crest",
    locality: "Whitefield",
    developerSlug: "salarpuria-sattva",
    projectType: "APARTMENT",
    totalUnits: 780,
    reraId: unverified("SATTVA", "001"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2017-08-03",
    validUntil: "2025-08-02",
    promisedPossession: "2023-06-30",
    actualPossession: "2024-03-31",
  },
  {
    key: "sattva:lumina",
    slug: "sattva-lumina",
    name: "Sattva Lumina",
    locality: "Whitefield",
    developerSlug: "salarpuria-sattva",
    projectType: "APARTMENT",
    totalUnits: 920,
    reraId: unverified("SATTVA", "002"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2021-12-16",
    validUntil: "2027-12-15",
    promisedPossession: "2026-12-31",
  },
  {
    key: "sattva:hamsa",
    slug: "sattva-hamsa",
    name: "Sattva Hamsa",
    locality: "Yelahanka",
    developerSlug: "salarpuria-sattva",
    projectType: "APARTMENT",
    totalUnits: 540,
    reraId: unverified("SATTVA", "003"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2020-03-09",
    validUntil: "2026-03-08",
    promisedPossession: "2025-06-30",
  },
  {
    key: "sattva:park-cubix",
    slug: "sattva-park-cubix",
    name: "Sattva Park Cubix",
    locality: "Whitefield",
    developerSlug: "salarpuria-sattva",
    projectType: "APARTMENT",
    totalUnits: 410,
    reraId: unverified("SATTVA", "004"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2018-05-21",
    validUntil: "2025-05-20",
    promisedPossession: "2023-12-31",
  },
  {
    key: "sattva:vasanta",
    slug: "sattva-vasanta-aharna",
    name: "Sattva Vasanta Aharna",
    locality: "Horamavu",
    developerSlug: "salarpuria-sattva",
    projectType: "APARTMENT",
    totalUnits: 360,
    reraId: unverified("SATTVA", "005"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2022-07-28",
    validUntil: "2027-07-27",
    promisedPossession: "2026-12-31",
  },
  {
    key: "embassy:springs",
    slug: "embassy-springs",
    name: "Embassy Springs",
    locality: "Devanahalli",
    developerSlug: "embassy-group",
    projectType: "MIXED",
    totalUnits: 3000,
    reraId: unverified("EMBASSY", "001"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2016-04-02",
    validUntil: "2026-04-01",
    promisedPossession: "2024-12-31",
  },
  {
    key: "embassy:lake-terraces",
    slug: "embassy-lake-terraces",
    name: "Embassy Lake Terraces",
    locality: "Hebbal",
    developerSlug: "embassy-group",
    projectType: "APARTMENT",
    totalUnits: 980,
    reraId: unverified("EMBASSY", "002"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2015-09-18",
    validUntil: "2024-09-17",
    promisedPossession: "2021-12-31",
    actualPossession: "2022-12-31",
  },
  {
    key: "embassy:boulevard",
    slug: "embassy-boulevard",
    name: "Embassy Boulevard",
    locality: "Yelahanka",
    developerSlug: "embassy-group",
    projectType: "VILLA",
    totalUnits: 220,
    reraId: unverified("EMBASSY", "003"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2017-11-11",
    validUntil: "2025-11-10",
    promisedPossession: "2023-06-30",
    actualPossession: "2023-12-31",
  },
  {
    key: "embassy:grove",
    slug: "embassy-grove",
    name: "Embassy Grove",
    locality: "Koramangala",
    developerSlug: "embassy-group",
    projectType: "APARTMENT",
    totalUnits: 90,
    reraId: unverified("EMBASSY", "004"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2018-02-06",
    validUntil: "2025-02-05",
    promisedPossession: "2022-12-31",
    actualPossession: "2023-06-30",
  },
  {
    key: "puravankara:atmosphere",
    slug: "purva-atmosphere",
    name: "Purva Atmosphere",
    locality: "Thanisandra",
    developerSlug: "puravankara",
    projectType: "APARTMENT",
    totalUnits: 680,
    reraId: unverified("PURAVANKARA", "001"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2020-08-14",
    validUntil: "2026-08-13",
    promisedPossession: "2025-12-31",
  },
  {
    key: "puravankara:zenium",
    slug: "purva-zenium",
    name: "Purva Zenium",
    locality: "Kengeri",
    developerSlug: "puravankara",
    projectType: "APARTMENT",
    totalUnits: 520,
    reraId: unverified("PURAVANKARA", "002"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2019-03-29",
    validUntil: "2026-03-28",
    promisedPossession: "2024-12-31",
  },
  {
    key: "puravankara:park-hill",
    slug: "purva-park-hill",
    name: "Purva Park Hill",
    locality: "Kanakapura Road",
    developerSlug: "puravankara",
    projectType: "APARTMENT",
    totalUnits: 440,
    reraId: unverified("PURAVANKARA", "003"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2017-06-23",
    validUntil: "2025-06-22",
    promisedPossession: "2023-06-30",
    actualPossession: "2024-03-31",
  },
  {
    key: "provident:ecopolitan",
    slug: "provident-ecopolitan",
    name: "Provident Ecopolitan",
    locality: "Whitefield",
    developerSlug: "puravankara",
    projectType: "APARTMENT",
    totalUnits: 1600,
    reraId: unverified("PURAVANKARA", "004"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2018-12-01",
    validUntil: "2026-11-30",
    promisedPossession: "2025-06-30",
  },
  {
    key: "assetz:marq",
    slug: "assetz-marq",
    name: "Assetz Marq",
    locality: "Whitefield",
    developerSlug: "assetz-property",
    projectType: "APARTMENT",
    totalUnits: 1400,
    reraId: unverified("ASSETZ", "001"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2017-04-13",
    validUntil: "2026-04-12",
    promisedPossession: "2024-12-31",
  },
  {
    key: "assetz:63-east",
    slug: "assetz-63-degree-east",
    name: "Assetz 63° East",
    locality: "Whitefield",
    developerSlug: "assetz-property",
    projectType: "APARTMENT",
    totalUnits: 890,
    reraId: unverified("ASSETZ", "002"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2019-09-06",
    validUntil: "2026-09-05",
    promisedPossession: "2025-09-30",
  },
  {
    key: "assetz:sun-sanctum",
    slug: "assetz-sun-and-sanctum",
    name: "Assetz Sun & Sanctum",
    locality: "Whitefield",
    developerSlug: "assetz-property",
    projectType: "APARTMENT",
    totalUnits: 470,
    reraId: unverified("ASSETZ", "003"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2018-01-17",
    validUntil: "2025-01-16",
    promisedPossession: "2023-12-31",
    actualPossession: "2024-06-30",
  },
  {
    key: "assetz:canvas-cove",
    slug: "assetz-canvas-and-cove",
    name: "Assetz Canvas & Cove",
    locality: "Yelahanka",
    developerSlug: "assetz-property",
    projectType: "APARTMENT",
    totalUnits: 620,
    reraId: unverified("ASSETZ", "004"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2022-05-25",
    validUntil: "2027-05-24",
    promisedPossession: "2026-12-31",
  },
  {
    key: "shriram:greenfield",
    slug: "shriram-greenfield",
    name: "Shriram Greenfield",
    locality: "Budigere Cross",
    developerSlug: "shriram-properties",
    projectType: "APARTMENT",
    totalUnits: 980,
    reraId: unverified("SHRIRAM", "001"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2018-06-19",
    validUntil: "2026-06-18",
    promisedPossession: "2024-12-31",
  },
  {
    key: "shriram:chirping-woods",
    slug: "shriram-chirping-woods",
    name: "Shriram Chirping Woods",
    locality: "Sarjapur Road",
    developerSlug: "shriram-properties",
    projectType: "APARTMENT",
    totalUnits: 540,
    reraId: unverified("SHRIRAM", "002"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2016-10-04",
    validUntil: "2024-10-03",
    promisedPossession: "2021-12-31",
    actualPossession: "2022-12-31",
  },
  {
    key: "shriram:codename-whitefield",
    slug: "shriram-codename-whitefield",
    name: "Shriram Codename Whitefield",
    locality: "Whitefield",
    developerSlug: "shriram-properties",
    projectType: "APARTMENT",
    totalUnits: 720,
    reraId: unverified("SHRIRAM", "003"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2022-11-08",
    validUntil: "2027-11-07",
    promisedPossession: "2027-03-31",
  },
  {
    key: "te:after-the-rain",
    slug: "total-environment-after-the-rain",
    name: "Total Environment After the Rain",
    locality: "Whitefield",
    developerSlug: "total-environment",
    projectType: "APARTMENT",
    totalUnits: 180,
    reraId: unverified("TOTALENV", "001"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2015-02-20",
    validUntil: "2023-02-19",
    promisedPossession: "2020-12-31",
    actualPossession: "2021-09-30",
  },
  {
    key: "te:pursuit",
    slug: "total-environment-pursuit-of-radical-rhapsody",
    name: "Total Environment Pursuit of Radical Rhapsody",
    locality: "Whitefield",
    developerSlug: "total-environment",
    projectType: "VILLA",
    totalUnits: 210,
    reraId: unverified("TOTALENV", "002"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2017-07-07",
    validUntil: "2025-07-06",
    promisedPossession: "2023-12-31",
    actualPossession: "2024-12-31",
  },
  {
    key: "te:learning-to-fly",
    slug: "total-environment-learning-to-fly",
    name: "Total Environment Learning to Fly",
    locality: "Yelahanka",
    developerSlug: "total-environment",
    projectType: "APARTMENT",
    totalUnits: 260,
    reraId: unverified("TOTALENV", "003"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2021-03-15",
    validUntil: "2027-03-14",
    promisedPossession: "2026-06-30",
  },
  {
    key: "mantri:webcity",
    slug: "mantri-webcity",
    name: "Mantri Webcity",
    locality: "Thanisandra",
    developerSlug: "mantri-developers",
    projectType: "APARTMENT",
    totalUnits: 1200,
    reraId: unverified("MANTRI", "001"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2014-08-01",
    validUntil: "2022-08-01",
    promisedPossession: "2019-12-31",
  },
  {
    key: "mantri:serenity",
    slug: "mantri-serenity",
    name: "Mantri Serenity",
    locality: "Kanakapura Road",
    developerSlug: "mantri-developers",
    projectType: "APARTMENT",
    totalUnits: 640,
    reraId: unverified("MANTRI", "002"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2016-01-14",
    validUntil: "2024-01-13",
    promisedPossession: "2021-06-30",
  },
  {
    key: "mantri:energia",
    slug: "mantri-energia",
    name: "Mantri Energia",
    locality: "Whitefield",
    developerSlug: "mantri-developers",
    projectType: "APARTMENT",
    totalUnits: 480,
    reraId: unverified("MANTRI", "003"),
    reraStatus: "UNVERIFIED",
    registeredOn: "2018-09-27",
    validUntil: "2025-09-26",
    promisedPossession: "2024-06-30",
  },
];
